name: API CI
#on: [push]
on:
  push:
    paths:
      - "./api/**"
      - ".github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./api

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          nove-version: 14
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json
      - name: install
        shell: bash
        run: npm ci #Instala dependencias en un entorno de integración continua
      - name: run test
        shell: bash
        run: npm run test
      - name: lint
        shell: bash
        run: npm run lint

